DB Changes:
  - any: ['dbScripts/DbScipts/*']
  - any: ['src/infrastructure/PersistanceLayer/*']
  - any: ['src/infrastructure/PersistanceLayerDapper/*']
BE:
  - any: ['*']
Tests:
  - any ['tests/*']

