name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./AlzaCaseStudy.sln
    - name: Build
      run: dotnet build ./src/presentation/API/API.csproj --no-restore
    - name: Test
      run: dotnet test tests/UnitTests/bin/Debug/net6.0/UnitTests.dll --no-build --verbosity normal
